# Generated by Django 5.0 on 2026-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='numreports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='usersThatHaveReported',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
